"""Add Note and Card tables

Revision ID: 3ce3917af8d0
Revises: c5d917d03885
Create Date: 2025-12-11 23:09:35.469627

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3ce3917af8d0'
down_revision: str | Sequence[str] | None = 'c5d917d03885'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notes',
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='所属用户ID'),
    sa.Column('deck_id', sa.String(length=36), nullable=False, comment='所属牌组ID'),
    sa.Column('note_model_id', sa.String(length=36), nullable=False, comment='笔记类型ID'),
    sa.Column('guid', sa.String(length=64), nullable=False, comment='语义唯一标识（用于共享牌组去重）'),
    sa.Column('fields', sa.JSON(), nullable=False, comment="字段内容，如 {'Front': 'apple', 'Back': '苹果'}"),
    sa.Column('tags', sa.JSON(), nullable=False, comment='标签列表'),
    sa.Column('source_type', sa.String(length=20), nullable=False, comment='来源类型: manual, ai, import'),
    sa.Column('source_meta', sa.JSON(), nullable=True, comment='来源元数据（AI 提示词、导入来源等）'),
    sa.Column('dirty', sa.Integer(), nullable=False, comment='是否有待同步变更: 0=否, 1=是'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键ID(UUID)'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='逻辑删除时间'),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.ForeignKeyConstraint(['note_model_id'], ['note_models.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_deck_id'), 'notes', ['deck_id'], unique=False)
    op.create_index(op.f('ix_notes_guid'), 'notes', ['guid'], unique=False)
    op.create_index(op.f('ix_notes_note_model_id'), 'notes', ['note_model_id'], unique=False)
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.create_table('cards',
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='所属用户ID'),
    sa.Column('note_id', sa.String(length=36), nullable=False, comment='所属笔记ID'),
    sa.Column('deck_id', sa.String(length=36), nullable=False, comment='所属牌组ID'),
    sa.Column('card_template_id', sa.String(length=36), nullable=False, comment='卡片模板ID'),
    sa.Column('ord', sa.Integer(), nullable=False, comment='模板序号（冗余字段）'),
    sa.Column('state', sa.String(length=20), nullable=False, comment='状态: new, learning, review, relearning'),
    sa.Column('queue', sa.String(length=20), nullable=False, comment='队列: new, learning, review, suspended'),
    sa.Column('due', sa.Integer(), nullable=False, comment='下次复习时间戳或天编号'),
    sa.Column('interval', sa.Integer(), nullable=False, comment='当前间隔（天）'),
    sa.Column('ease_factor', sa.Integer(), nullable=False, comment='难度系数（2500=2.5）'),
    sa.Column('reps', sa.Integer(), nullable=False, comment='复习次数'),
    sa.Column('lapses', sa.Integer(), nullable=False, comment='遗忘次数'),
    sa.Column('last_review', sa.Integer(), nullable=True, comment='上次复习时间戳'),
    sa.Column('stability', sa.Float(), nullable=False, comment='FSRS 稳定性'),
    sa.Column('difficulty', sa.Float(), nullable=False, comment='FSRS 难度'),
    sa.Column('dirty', sa.Integer(), nullable=False, comment='是否有待同步变更: 0=否, 1=是'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键ID(UUID)'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='逻辑删除时间'),
    sa.ForeignKeyConstraint(['card_template_id'], ['card_templates.id'], ),
    sa.ForeignKeyConstraint(['deck_id'], ['decks.id'], ),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cards_card_template_id'), 'cards', ['card_template_id'], unique=False)
    op.create_index(op.f('ix_cards_deck_id'), 'cards', ['deck_id'], unique=False)
    op.create_index(op.f('ix_cards_note_id'), 'cards', ['note_id'], unique=False)
    op.create_index(op.f('ix_cards_user_id'), 'cards', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cards_user_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_note_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_deck_id'), table_name='cards')
    op.drop_index(op.f('ix_cards_card_template_id'), table_name='cards')
    op.drop_table('cards')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_note_model_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_guid'), table_name='notes')
    op.drop_index(op.f('ix_notes_deck_id'), table_name='notes')
    op.drop_table('notes')
    # ### end Alembic commands ###
