"""Add ReviewLog table

Revision ID: 48991fbf71f4
Revises: 3ce3917af8d0
Create Date: 2025-12-11 23:10:58.474001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48991fbf71f4'
down_revision: Union[str, Sequence[str], None] = '3ce3917af8d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_logs',
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='所属用户ID'),
    sa.Column('card_id', sa.String(length=36), nullable=False, comment='所属卡片ID'),
    sa.Column('review_time', sa.BigInteger(), nullable=False, comment='复习时间戳（毫秒）'),
    sa.Column('rating', sa.Integer(), nullable=False, comment='用户评分: 1=Again, 2=Hard, 3=Good, 4=Easy'),
    sa.Column('prev_state', sa.String(length=20), nullable=True, comment='复习前状态'),
    sa.Column('new_state', sa.String(length=20), nullable=True, comment='复习后状态'),
    sa.Column('prev_interval', sa.Integer(), nullable=True, comment='复习前间隔（天）'),
    sa.Column('new_interval', sa.Integer(), nullable=True, comment='复习后间隔（天）'),
    sa.Column('prev_ease_factor', sa.Integer(), nullable=True, comment='复习前难度系数'),
    sa.Column('new_ease_factor', sa.Integer(), nullable=True, comment='复习后难度系数'),
    sa.Column('prev_due', sa.BigInteger(), nullable=True, comment='复习前到期时间'),
    sa.Column('new_due', sa.BigInteger(), nullable=True, comment='复习后到期时间'),
    sa.Column('prev_stability', sa.Float(), nullable=True, comment='复习前稳定性'),
    sa.Column('new_stability', sa.Float(), nullable=True, comment='复习后稳定性'),
    sa.Column('prev_difficulty', sa.Float(), nullable=True, comment='复习前难度'),
    sa.Column('new_difficulty', sa.Float(), nullable=True, comment='复习后难度'),
    sa.Column('duration_ms', sa.Integer(), nullable=True, comment='本次回答耗时（毫秒）'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键ID(UUID)'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='逻辑删除时间'),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_logs_card_id'), 'review_logs', ['card_id'], unique=False)
    op.create_index(op.f('ix_review_logs_review_time'), 'review_logs', ['review_time'], unique=False)
    op.create_index(op.f('ix_review_logs_user_id'), 'review_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_review_logs_user_id'), table_name='review_logs')
    op.drop_index(op.f('ix_review_logs_review_time'), table_name='review_logs')
    op.drop_index(op.f('ix_review_logs_card_id'), table_name='review_logs')
    op.drop_table('review_logs')
    # ### end Alembic commands ###
