"""Add NoteModel and CardTemplate tables

Revision ID: 82dffcbc31fa
Revises: 
Create Date: 2025-12-11 23:04:59.881367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82dffcbc31fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('email', sa.String(length=100), nullable=False, comment='邮箱'),
    sa.Column('nickname', sa.String(length=50), nullable=False, comment='昵称'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='加密密码'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否激活'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='是否超级管理员'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键ID(UUID)'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='逻辑删除时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('note_models',
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='所属用户ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='笔记类型名称'),
    sa.Column('fields_schema', sa.JSON(), nullable=False, comment="字段定义，如 [{'name': 'Front'}, {'name': 'Back'}]"),
    sa.Column('css', sa.Text(), nullable=True, comment='自定义CSS样式'),
    sa.Column('is_builtin', sa.Boolean(), nullable=False, server_default='0', comment='是否内置/预设模板'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键ID(UUID)'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='逻辑删除时间'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_note_models_user_id'), 'note_models', ['user_id'], unique=False)
    op.create_index(op.f('ix_note_models_is_builtin'), 'note_models', ['is_builtin'], unique=False)
    op.create_table('card_templates',
    sa.Column('note_model_id', sa.String(length=36), nullable=False, comment='所属笔记类型ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='模板名称'),
    sa.Column('ord', sa.Integer(), nullable=False, comment='模板序号（从0开始）'),
    sa.Column('question_template', sa.Text(), nullable=False, comment='问题侧HTML模板'),
    sa.Column('answer_template', sa.Text(), nullable=False, comment='答案侧HTML模板'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键ID(UUID)'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='逻辑删除时间'),
    sa.ForeignKeyConstraint(['note_model_id'], ['note_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_card_templates_note_model_id'), 'card_templates', ['note_model_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_card_templates_note_model_id'), table_name='card_templates')
    op.drop_table('card_templates')
    op.drop_index(op.f('ix_note_models_is_builtin'), table_name='note_models')
    op.drop_index(op.f('ix_note_models_user_id'), table_name='note_models')
    op.drop_table('note_models')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
