"""Add SharedDeck and TemplateSet tables

Revision ID: b314fe7b75ca
Revises: 48991fbf71f4
Create Date: 2025-12-11 23:13:11.412202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b314fe7b75ca'
down_revision: Union[str, Sequence[str], None] = '48991fbf71f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 注意: template_sets 表已被移除，不再创建
    op.create_table('shared_decks',
    sa.Column('author_id', sa.String(length=36), nullable=False, comment='作者用户ID'),
    sa.Column('slug', sa.String(length=100), nullable=False, comment='URL 友好标识'),
    sa.Column('title', sa.String(length=200), nullable=False, comment='标题'),
    sa.Column('description', sa.Text(), nullable=True, comment='描述（Markdown）'),
    sa.Column('language', sa.String(length=10), nullable=False, comment='语言'),
    sa.Column('tags', sa.JSON(), nullable=False, comment='标签列表'),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True, comment='封面图片URL'),
    sa.Column('card_count', sa.Integer(), nullable=False, comment='卡片数量'),
    sa.Column('note_count', sa.Integer(), nullable=False, comment='笔记数量'),
    sa.Column('download_count', sa.Integer(), nullable=False, comment='下载次数'),
    sa.Column('version', sa.Integer(), nullable=False, comment='当前版本号'),
    sa.Column('content_hash', sa.String(length=64), nullable=True, comment='内容哈希'),
    sa.Column('is_featured', sa.Boolean(), nullable=False, comment='是否精选'),
    sa.Column('is_official', sa.Boolean(), nullable=False, comment='是否官方'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否上架'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键ID(UUID)'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='逻辑删除时间'),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_decks_author_id'), 'shared_decks', ['author_id'], unique=False)
    op.create_index(op.f('ix_shared_decks_slug'), 'shared_decks', ['slug'], unique=True)
    op.create_table('shared_deck_snapshots',
    sa.Column('shared_deck_id', sa.String(length=36), nullable=False, comment='共享牌组ID'),
    sa.Column('version', sa.Integer(), nullable=False, comment='版本号'),
    sa.Column('export_format_version', sa.Integer(), nullable=False, comment='导出格式版本'),
    sa.Column('file_url', sa.String(length=500), nullable=False, comment='文件URL'),
    sa.Column('content_hash', sa.String(length=64), nullable=False, comment='内容哈希'),
    sa.Column('file_size', sa.Integer(), nullable=True, comment='文件大小（字节）'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键ID(UUID)'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='逻辑删除时间'),
    sa.ForeignKeyConstraint(['shared_deck_id'], ['shared_decks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shared_deck_snapshots_shared_deck_id'), 'shared_deck_snapshots', ['shared_deck_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shared_deck_snapshots_shared_deck_id'), table_name='shared_deck_snapshots')
    op.drop_table('shared_deck_snapshots')
    op.drop_index(op.f('ix_shared_decks_slug'), table_name='shared_decks')
    op.drop_index(op.f('ix_shared_decks_author_id'), table_name='shared_decks')
    op.drop_table('shared_decks')
    # 注意: template_sets 表已被移除，不再创建
    # ### end Alembic commands ###
