"""Add Deck table

Revision ID: c5d917d03885
Revises: 82dffcbc31fa
Create Date: 2025-12-11 23:06:44.498670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5d917d03885'
down_revision: Union[str, Sequence[str], None] = '82dffcbc31fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decks',
    sa.Column('user_id', sa.String(length=36), nullable=False, comment='所属用户ID'),
    sa.Column('name', sa.String(length=100), nullable=False, comment='牌组名称'),
    sa.Column('parent_id', sa.String(length=36), nullable=True, comment='父牌组ID'),
    sa.Column('note_model_id', sa.String(length=36), nullable=True, comment='绑定的笔记类型ID'),
    sa.Column('config', sa.JSON(), nullable=False, comment='牌组配置（每日新卡数、复习数、学习步骤等）'),
    sa.Column('scheduler', sa.String(length=20), nullable=False, comment='调度算法: sm2, fsrs_v4, fsrs_v5'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='牌组描述'),
    sa.Column('id', sa.String(length=36), nullable=False, comment='主键ID(UUID)'),
    sa.Column('created_by', sa.String(length=50), nullable=True, comment='创建人'),
    sa.Column('updated_by', sa.String(length=50), nullable=True, comment='更新人'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='逻辑删除时间'),
    sa.ForeignKeyConstraint(['note_model_id'], ['note_models.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['decks.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decks_note_model_id'), 'decks', ['note_model_id'], unique=False)
    op.create_index(op.f('ix_decks_parent_id'), 'decks', ['parent_id'], unique=False)
    op.create_index(op.f('ix_decks_user_id'), 'decks', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_decks_user_id'), table_name='decks')
    op.drop_index(op.f('ix_decks_parent_id'), table_name='decks')
    op.drop_index(op.f('ix_decks_note_model_id'), table_name='decks')
    op.drop_table('decks')
    # ### end Alembic commands ###
